// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Carbon:cloudUpload': typeof import('~icons/carbon/cloud-upload')['default']
    'Carbon:password': typeof import('~icons/carbon/password')['default']
    'Carbon:userAvatarFilledAlt': typeof import('~icons/carbon/user-avatar-filled-alt')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    CarbonWarning: typeof import('~icons/carbon/warning')['default']
    CompaniesTable: typeof import('./companies/components/companiesTable.vue')['default']
    DetailsDrawer: typeof import('./companies/components/detailsDrawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImportDrawer: typeof import('./companies/components/importDrawer.vue')['default']
    KModal: typeof import('./common/components/k-modal.vue')['default']
    Navbar: typeof import('./common/components/dashboard/Navbar.vue')['default']
    Sidebar: typeof import('./common/components/dashboard/Sidebar.vue')['default']
  }
}

export { }
